export const products = {
  "1": {
    id: "1",
    name: "Sourdough Bread",
    description: "Traditional sourdough bread made with organic flour. Our signature sourdough is fermented for 24 hours, creating a perfect balance of tangy flavor and chewy texture. Made with organic wheat flour, filtered water, and our century-old starter culture.",
    price: 8.99,
    allergens: ["wheat", "gluten"],
    quantity: 10,
    tags: ["bread", "organic"],
    enabled: true,
    featured: true,
    image: "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?q=80&w=2070",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  "2": {
    id: "2",
    name: "Chocolate Croissant",
    description: "Buttery croissant filled with premium dark chocolate. Each croissant is hand-laminated over three days, creating 27 perfect layers of butter and dough. Filled with high-quality 70% dark chocolate from single-origin cacao beans.",
    price: 4.99,
    allergens: ["wheat", "dairy", "eggs"],
    quantity: 15,
    tags: ["pastries", "chocolate"],
    enabled: true,
    featured: true,
    image: "https://images.unsplash.com/photo-1530610476181-d83430b64dcd?q=80&w=2070",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
};